// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsGCSiyh54ocKRzHYYYojpQTsy01UK6gI',
    appId: '1:958006601823:web:dbacddfdd22d7b3d7b13ea',
    messagingSenderId: '958006601823',
    projectId: 'usermanagemeentapp',
    authDomain: 'usermanagemeentapp.firebaseapp.com',
    storageBucket: 'usermanagemeentapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc4Jm5wNjihJ29QKY9G7M7sSdHz6-HJl0',
    appId: '1:958006601823:android:0e9499e98085e3eb7b13ea',
    messagingSenderId: '958006601823',
    projectId: 'usermanagemeentapp',
    storageBucket: 'usermanagemeentapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWVg5DjTkFJfBvM_UFuUDkptX4SKTlj6M',
    appId: '1:958006601823:ios:3124c92f60d857c77b13ea',
    messagingSenderId: '958006601823',
    projectId: 'usermanagemeentapp',
    storageBucket: 'usermanagemeentapp.appspot.com',
    iosBundleId: 'com.example.usermanagementapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWVg5DjTkFJfBvM_UFuUDkptX4SKTlj6M',
    appId: '1:958006601823:ios:8e99bfcf3c40bd0f7b13ea',
    messagingSenderId: '958006601823',
    projectId: 'usermanagemeentapp',
    storageBucket: 'usermanagemeentapp.appspot.com',
    iosBundleId: 'com.example.usermanagementapp.RunnerTests',
  );
}
